### ISSUE TITLE
Bug: Streamystats Header missing Access Token

### ISSUE THREAD

**Issue by retardgerman** [Schaka/janitorr#150]
```
java.lang.IllegalStateException: Header missing streamystats-token
        at com.github.schaka.janitorr.stats.streamystats.StreamystatsClientConfig$StreamystatsUserinterceptor.apply(StreamystatsClientConfig.kt:52) ~[na:na]
        at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:120) ~[na:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:78) ~[na:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:53) ~[na:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:104) ~[na:na]
        at jdk.proxy4/jdk.proxy4.$Proxy/sbad3ec21.getRequests(Unknown Source) ~[na:na]
        at com.github.schaka.janitorr.stats.streamystats.StreamystatsRestService.gracefulQuery(StreamystatsRestService.kt:70) ~[na:na]
        at com.github.schaka.janitorr.stats.streamystats.StreamystatsRestService.populateWatchHistory(StreamystatsRestService.kt:45) ~[na:na]
        at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.cleanupMediaType(AbstractCleanupSchedule.kt:74) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete(AbstractCleanupSchedule.kt:52) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at com.github.schaka.janitorr.cleanup.TagBasedCleanupSchedule.runSchedule(TagBasedCleanupSchedule.kt:61) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at java.base@24/java.lang.reflect.Method.invoke(Method.java:565) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[na:na]
        at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:55) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:430) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:565) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:447) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:409) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:65) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[na:na]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:727) ~[na:na]
        at com.github.schaka.janitorr.cleanup.TagBasedCleanupSchedule$$SpringCGLIB$$0.runSchedule(<generated>) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at java.base@24/java.lang.reflect.Method.invoke(Method.java:565) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[na:na]
        at io.micrometer.observation.Observation.observe(Observation.java:498) ~[com.github.schaka.janitorr.JanitorrApplicationKt:1.14.5]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[na:na]
        at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[na:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[com.github.schaka.janitorr.JanitorrApplicationKt:6.2.5]
        at java.base@24/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545) ~[na:na]
        at java.base@24/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:369) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at java.base@24/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:310) ~[na:na]
        at java.base@24/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at java.base@24/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619) ~[na:na]
        at java.base@24/java.lang.Thread.runWith(Thread.java:1460) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at java.base@24/java.lang.VirtualThread.run(VirtualThread.java:466) ~[com.github.schaka.janitorr.JanitorrApplicationKt:na]
        at java.base@24/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:258) ~[na:na]

```

I don't know if this is a problem with janitorr or with streamystats.

**Comment by retardgerman** [comment]
> Streamystats is completely broken with no fix in sight: [fredrikburmester/streamystats#113](https://github.com/fredrikburmester/streamystats/issues/113) [fredrikburmester/streamystats#134](https://github.com/fredrikburmester/streamystats/issues/134)
> 
> I suggest to stick to a version before 1.7.x. I can't support any version after that, unless it's stable again. Can't even get it to run myself to test against any updates. I'd highly recommend Jellystat instead, until Streamystats becomes more stable or other maintainers jump on.
> 
> The error you're seeing is because Streamystats doesn't respond to login requests with the correct header that's required to perform API requests.

Okay, I see. I'm in direct talks with Fredrik, I'll have a chat with him. As far as I know, v2 is also in the works and about to be released

**Comment by Schaka** [comment]
You may try the latest develop image once it's finished building. If you use any of the more precise tags, you won't need to wait for the ARM build to finish.

@fredrikburmester can you maybe elaborate where the `'Next-Action'` header stems from?
Streamystats won't accept any login requests without it and without a login request, I cannot get a valid token because Streamystats doesn't have independent API keys.

**Comment by Schaka** [comment]
Can you ping him, @retardgerman?

**Comment by fredrikburmester** [comment]
Sorry guys I forgot to migrate the endpoint to V2, but i've now implemented the details endpoint in V2. 
--
I've implemented an endpoint `/servers/[serverId]/items/[itemId]/details` in Streamystats V2. 
It returns similar data, but in a different structure (can look into a better structure if wanted)
You need the correct cookies for this API endpoint so you need to POST to `/api/servers/[serverId]/login` first
It's currently building, but please try it out when it's finished.

**Comment by fredrikburmester** [comment]
I just realized that we maybe don't want to specify the server id in the request? I can remove that if you guys want.

**Comment by fredrikburmester** [comment]
I don't require that header explicitly. It should work without it in the latest version of v2.

**Comment by Schaka** [comment]
The problem remains, unfortunately.

Any request to `streamyfin.host/servers/1/login` will be reject and you WILL be redirected to the login page (form).
If you supply the correct `Next-Action` header of `7fbcd059773d0cb8312c1652380aeae2821d3534e2` (for 2.2.0), the login request is considered valid.

You may not explicitly require this, but whatever framework you're using most likely is.

Hopefully the attached screenshot helps:

<img width="1898" height="861" alt="Image" src="https://github.com/user-attachments/assets/4886566f-d250-4cec-9970-3eff457a2e1e" />

**Comment by fredrikburmester** [comment]
Well the login page you're trying to POST to is just a normal page, not an API endpoint. Maybe this should work, but i don't know that for a fact.

That's why I've created a new endpoint for logging in via a normal API POST request that should work `/api/servers/[serverId]/login`

**Comment by fredrikburmester** [comment]
I have quite a unique implementation where if you're an admin you'll see all stats, and if not you'll only see your own stats. I might have a bug there.

**Comment by Schaka** [comment]
How do you determine admin? I bet that's it.

My Jellyfin automation user has limited permissions for security reasons. 

According to the [Jellyfin docs](https://jellyfin.org/docs/general/server/users/#administrators) , it's just one option that determines admin privileges. This one is activated for my user - but managing collections and subtitles are not.

Just for testing purposes, I used my non-automation user (also admin by Jellyfin's definition) and requested stats for media that I definitely watched myself (taken from Streamystats 'Me' menu item). Unfortuantely that resulted in another 404.

**Comment by fredrikburmester** [comment]
Ah sorry haha, I was already thinking about the snake_case fields and wanted to change them so i got confused. I totally agree with you though with the URL.

**Comment by Schaka** [comment]
I noticed you're using 2 different time formats:

<img width="519" height="271" alt="Image" src="https://github.com/user-attachments/assets/5ce42e0d-4ffd-4a1a-8246-9dd2b189cee7" />

Other than that, I looked at your code and I'm almost done with my implementation. Looks good so far.

**Comment by Schaka** [comment]
@retardgerman this is now implemented in the latest develop image. You may grab it and give it a try.
I've done limited testing, but more real data to find potential bugs is going to help.

**Comment by Schaka** [comment]
> I'm sorry, I'm not sure what you are referring to in the image?

`firstWatched`, `lastWatched` and `watchDate` are all DateTime formats but they're different patterns.

watchDate at least seems to be a match for ISO-8601, so I'd stick with that for the others too.

**Comment by Schaka** [comment]
@retardgerman you may try the develop image. If it works for you, I'll merge it up. In my limited testing it looked good.

**Comment by retardgerman** [comment]
@Schaka It seems to work fine. I can't see any strange logs or anything.

**Comment by Schaka** [comment]
v1.7.3 will have official support for 2.4.0+

It also withstood my testing. Anything more will have to come in via bug reports.
