### ISSUE TITLE
Request: When added to the leaving soon collection items lose their metadata. (Emby Issue)

### ISSUE THREAD

**Issue by hacshacdgacs** [Schaka/janitorr#48]
As stated above. Currently with Emby when something is added to leaving soon it doesn't take any metadata with it so it ends up looking like this in the library. 
![image](https://github.com/user-attachments/assets/11169ab1-50a8-4771-a5ca-c5d7fed26ae8)
In it's original directory that movies has all the following files in it's directory 
![image](https://github.com/user-attachments/assets/59824fe7-6e30-4b1d-aae7-aa98af9a3a44)
and looks like this in the "movies" library.
![image](https://github.com/user-attachments/assets/63246bd5-c34e-4291-b21b-224df0dcdb9f)
Currently janitorr only takes the movie file over to the leaving soon library and if it were to take all the files across it would keep it's metadata attached.
![image](https://github.com/user-attachments/assets/b7e10b24-49e6-4ac9-971e-43dd27183480)

**Comment by hacshacdgacs** [comment]
After adding those files to the leaving soon folder Emby regained the metadata (mostly, in the normal library the imdbid is ignored but isnt in the leaving soon library, I believe cause of the lack of metadata on the original import)
![image](https://github.com/user-attachments/assets/bfb956f1-abda-48e5-a987-945486f0d1a4)

![image](https://github.com/user-attachments/assets/81c3d0af-e3d8-40d7-bb0b-2e0264e28aad)

**Comment by hacshacdgacs** [comment]
Actually looking into it a bit more the leaving soon category despite having the same folder structure as the movies library is displaying the folders as the top level (hence the wrong naming format).
Movies Library
Top level:
![image](https://github.com/user-attachments/assets/d931ffa5-f525-4a52-9109-05a45ab6f22a)
Next level:
![image](https://github.com/user-attachments/assets/67a2c79e-a014-4574-bcbe-cc7e03feccbe)
Whereas the leaving soon goes
Top level:
![image](https://github.com/user-attachments/assets/e07df193-a0de-44ad-bcce-d742769c9416)
Next level:
![image](https://github.com/user-attachments/assets/cb12eed1-4509-4a56-bd0d-0e044cf9fced)
Next level:
![image](https://github.com/user-attachments/assets/db313882-64a3-4f18-8a25-6a4ea070f3bf)
So the second level is portraying the correct naming format like it would in the normal movies library.
![image](https://github.com/user-attachments/assets/45b384b3-f4d4-4c80-82e0-3ed9830803ec)
It does so on one without the metadata attached also. It seems as if the leaving soon library is being treated more like collections than an actual library so is presenting itself oddly

**Comment by Schaka** [comment]
> Currently janitorr only takes the movie file over to the leaving soon library and if it were to take all the files across it would keep > it's metadata attached.

This is correct. Only movie files are touched. This is especially important for cleanup - but also because there's no control over whether Jellyfin/Emby keeps metadata with the files or in its database. Those libraries should be auto scanned and have metadata added automatically.

> It does so on one without the metadata attached also. It seems as if the leaving soon library is being treated more like > collections than an actual library so is presenting itself oddly

While this isn't intended, the folder structure itself is most certainly correct. You may have disabled collections for your regular libraries, but generally speaking, those are managed by the server automatically. Not much you can do but turn them off.
The type of library is clearly set as either `Movies` or `Tv`.

It's [this API call](https://dev.emby.media/reference/RestAPI/LibraryStructureService/postLibraryVirtualfolders.html#Emby_Api_Library_AddVirtualFolder) we're talking about. Since there are basically no explanations given at all, I just went by what Jellyfin uses and what I was able to reverse engineer for Emby. 

I know this likely isn't what you wanted to hear, but since Emby is secondary to me, you're probably not going to get this changed. It would require splitting Emby and Jellyfin up properly and officially having to support Emby on every change I make.

I'll leave this ticket up for at least a few days while I think about whether I want to take on that work.

**Comment by hacshacdgacs** [comment]
For what it's worth I've never had the metadata attach itself onto the leaving soon libraries.
The libraries are also being viewed as having no collections (and do have the collections option off) but they're being presented as if every single movie is a collection of its own. 
I understand Emby being secondary to you and that these are most likely errors simply due to how Emby itself handles things (and their lack of documentation) so I appreciate the fact you included it in the first place.

**Comment by Schaka** [comment]
> Regarding this, wouldn't from-scratch: true overcome this issue? I ask this because having from-scratch enabled happened to delete the metadata I had manually added earlier haha

It should, yes. But if people aren't using it, things will get even more complicated. Generally, Janitorr finds all media with a certain IMDB id and deletes it if mediaserver deletion is enabled. This should remove your media (and hopefully metatdata) without needing the from-scratch option as well. It works in Jellyfin at least.

When comparing folder structures in your main library and the leaving soon collections, is there anything you can spot that looks different/off? In my simple testing setup, both media server are just pointed to the same folders  and everything looks the same from what I can tell.

For leaving soon, the root folder gets a subfolder where each type of cleanup (tag based, media based) gets its own sub folder. It should look like this: `/leaving-soon/movies/tag-based/Movie [imdb-tt1823123]/Movie  [imdb-tt1823123.mkv`. This is assuming correct Radarr settings. It *should* be picked up correctly and not weirdly like a collection in Emby/Jellyfin.

If there are any leftover folders or your leaving soon libraries point to any other folders, you'll likely have to manually correct this.

**Comment by hacshacdgacs** [comment]
The movies filepath:
/DATA/Media/Movies/28 Days Later (2002) [imdbid-tt0289043]/28 Days Later (2002) [imdbid-tt0289043] - [DTS][Bluray-1080p Proper][DTS 5.1][x264]-wsp.mkv
The leaving soon filepath:
/DATA/Media/Leaving Soon/movies/media/28 Days Later (2002) [imdbid-tt0289043]/28 Days Later (2002) [imdbid-tt0289043] - [DTS][Bluray-1080p Proper][DTS 5.1][x264]-wsp.mkv
To my eyes it looks correct, I have noticed in JellyStat however that the leaving soon libraries are being considered as mixed content and not series or movies (again seeming to be part of the emby api issue).
![image](https://github.com/user-attachments/assets/03aae8d6-8d38-457b-a84c-9242a4dd05d5)

**Comment by Schaka** [comment]
Valid collectionType arguments according to Jellyfin are Movies and TvShows (spelled exactly like that).
Maybe you can look at the requests Emby sends in your web interface and check which types your existing collections are.

I definitely don't set "Mixed" actively.  It seems Emby is actively reworking their API into removing a lot of the old parameters Jellyfin was using and uses proper transfer objects now.

Please delete your leaving soon libraries in Emby and on your drive, then try the latest develop image.

**Comment by hacshacdgacs** [comment]
I have deleted and updated and same problem unfortunately.
![image](https://github.com/user-attachments/assets/5c7592db-a807-40b4-b1bb-ef2aed2ccf78)
Emby itself is saying that library is a Movies one but JellyStat still thinks mixed which is odd. In terms of TV Shows Emby has now added a space it seems
![image](https://github.com/user-attachments/assets/abece84c-6755-4902-96fb-ce268ca73af2)
![image](https://github.com/user-attachments/assets/e1c1456c-92af-44f7-a3c0-529f31b6e07a)

**Comment by Schaka** [comment]
I think I need to find out what types exactly Emby expects. If you edit the library, does it show the correct type, or is nothing selected in the dropdown because an incorrect value was supplied previously (by me)?

I would assume Movies should at least be correct, whereas TV shows should likely be called "TV shows" for Emby.

**Comment by hacshacdgacs** [comment]
Fun part about emby is you cant change the content type of a library that already exists 
![image](https://github.com/user-attachments/assets/b0a7e9dd-7954-47a7-bb84-3f72849aff9a)
However these are the options for a new library
![image](https://github.com/user-attachments/assets/bc5c2718-6839-4b97-9a6f-8e76574184de)

**Comment by Schaka** [comment]
Please try the latest develop image again. I made some changes in hopes that the web UI is using things mostly correctly and I only have to follow that and ignore the API docs for now.

**Comment by hacshacdgacs** [comment]
Fails to work with the latest develop, it creates the shows library but doesn't add things to it. The movies library doesn't get created at all. The shows library is matching on content type however, even according to JellyStat
![image](https://github.com/user-attachments/assets/bf05b5ca-85f9-4f7c-9466-21aaf87f45db)
![image](https://github.com/user-attachments/assets/70d0c065-310e-4a9b-b8f1-94ab96ab551e)
Below is the code showing the error.
> janitorr-1  | feign.FeignException: Instantiation of [simple type, class com.github.schaka.janitorr.mediaserver.library.LibraryOptions] value failed for JSON property TypeOptions due to missing (therefore NULL) value for creator parameter TypeOptions which is a non-nullable type
janitorr-1  |  at [Source: (BufferedReader); line: 1, column: 18904] (through reference chain: java.util.ArrayList[7]->com.github.schaka.janitorr.mediaserver.library.VirtualFolderResponse["LibraryOptions"]->com.github.schaka.janitorr.mediaserver.library.LibraryOptions["TypeOptions"]) reading GET http://192.168.68.179:8096/emby/Library/VirtualFolders

**Comment by Schaka** [comment]
Going to have to ask you to try the latest develop image again. Hopefully that was the only issue with the return type. It seems at least library type creation is fixed now, so as soon as I get the REST API response I'm hoping for, everything should work as expected

**Comment by hacshacdgacs** [comment]
> janitorr-1  | 2024-07-16T18:49:26.770+12:00 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
> janitorr-1  | 
> janitorr-1  | feign.FeignException: Instantiation of [simple type, class com.github.schaka.janitorr.mediaserver.library.TypeOption] value failed for JSON property DefaultImageOptions due to missing (therefore NULL) value for creator parameter DefaultImageOptions which is a non-nullable type
> janitorr-1  |  at [Source: (BufferedReader); line: 1, column: 1826] (through reference chain: java.util.ArrayList[0]->com.github.schaka.janitorr.mediaserver.library.VirtualFolderResponse["LibraryOptions"]->com.github.schaka.janitorr.mediaserver.library.LibraryOptions["TypeOptions"]->java.util.ArrayList[0]->com.github.schaka.janitorr.mediaserver.library.TypeOption["DefaultImageOptions"]) reading GET http://192.168.68.179:8096/emby/Library/VirtualFolders
> janitorr-1  | 	at feign.FeignException.errorReading(FeignException.java:167) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at feign.InvocationContext.decode(InvocationContext.java:120) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at feign.InvocationContext.proceed(InvocationContext.java:88) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	at jdk.proxy2/jdk.proxy2.$Proxy77.listLibraries(Unknown Source) ~[na:na]
> janitorr-1  | 	at com.github.schaka.janitorr.mediaserver.emby.EmbyRestService.updateLeavingSoon(EmbyRestService.kt:42) ~[classes/:na]
> janitorr-1  | 	at com.github.schaka.janitorr.mediaserver.MediaServerService.updateLeavingSoon$default(MediaServerService.kt:31) ~[classes/:na]
> janitorr-1  | 	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.cleanupMediaType(AbstractCleanupSchedule.kt:73) ~[classes/:na]
> janitorr-1  | 	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete(AbstractCleanupSchedule.kt:49) ~[classes/:na]
> janitorr-1  | 	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete$default(AbstractCleanupSchedule.kt:33) ~[classes/:na]
> janitorr-1  | 	at com.github.schaka.janitorr.cleanup.MediaCleanupSchedule.runSchedule(MediaCleanupSchedule.kt:50) ~[classes/:na]
> janitorr-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
> janitorr-1  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:416) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:545) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:433) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.5.jar:6.1.5]
> janitorr-1  | 	at com.github.schaka.janitorr.cleanup.MediaCleanupSchedule$$SpringCGLIB$$0.runSchedule() ~[classes/:na]
> janitorr-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
> janitorr-1  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.4.jar:1.12.4]
> janitorr-1  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.5.jar:6.1.5]
> janitorr-1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
> janitorr-1  | 	at java.base/java.lang.VirtualThread.run(Unknown Source) ~[na:na]
> janitorr-1  | Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.github.schaka.janitorr.mediaserver.library.TypeOption] value failed for JSON property DefaultImageOptions due to missing (therefore NULL) value for creator parameter DefaultImageOptions which is a non-nullable type
> janitorr-1  |  at [Source: (BufferedReader); line: 1, column: 1826] (through reference chain: java.util.ArrayList[0]->com.github.schaka.janitorr.mediaserver.library.VirtualFolderResponse["LibraryOptions"]->com.github.schaka.janitorr.mediaserver.library.LibraryOptions["TypeOptions"]->java.util.ArrayList[0]->com.github.schaka.janitorr.mediaserver.library.TypeOption["DefaultImageOptions"])
> janitorr-1  | 	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84) ~[jackson-module-kotlin-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:525) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1419) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1419) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1419) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3801) ~[jackson-databind-2.15.4.jar:2.15.4]
> janitorr-1  | 	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-13.1.jar:na]
> janitorr-1  | 	at feign.InvocationContext.decode(InvocationContext.java:114) ~[feign-core-13.1.jar:na]
> janitorr-1  | 	... 41 common frames omitted

That's with the latest develop image

**Comment by Schaka** [comment]
Seems like their docs were incorrect. I removed the offending field entirely. Please try again.
Thanks for bearing with me. I can only look at what responses I'm getting locally, but they can vary wildly depending on what media you actually own - so I'm limited in my testing.

**Comment by hacshacdgacs** [comment]
Fair enough, thanks for pushing through the emby side. This latest image seems to have done the trick. Both libraries were created and both have been recognised as what they are so are portraying properly. 

Despite that however it's still failing to provide any images or metadata (emby itself is failing to find any for them like it normally would so I'm assuming just an emby issue on this part now)
![image](https://github.com/user-attachments/assets/11f797f1-76fc-45ef-8f85-be8c15794518)
![image](https://github.com/user-attachments/assets/931d1609-e83b-4e97-8d00-684429161067)

Below is with me manually placing the files that were with the original movie file into the leaving soon items (and said files).

![image](https://github.com/user-attachments/assets/bb14a3ab-6d9e-4b09-8566-a662bb50f457)
![image](https://github.com/user-attachments/assets/ec3ba8aa-eca0-42c4-b8b7-8ad77a6bb3c4)

**Comment by hacshacdgacs** [comment]
It seems like because Emby has already found the metadata for the item at the old location (movies) it doesn't try and create any for it at the new location (leaving-soon) even if try and force it to replace the metadata.

**Comment by Schaka** [comment]
That seems to be an Emby specific problem. I'm not sure I want to adjust how I copy files for that. Maybe you can raise an issue with them.

**Comment by hacshacdgacs** [comment]
Fair enough, I'll do that and see if they do anything about it. Thank you

**Comment by Schaka** [comment]
I'll close this then. If they are completely against fixing this, open a new ticket and I'll look into doing it in Janitorr.
